spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


server:
  port: 8080

build:
  version: "1.0"

accounts:
  message: "Welcome to QBank related local APIs"
  contactDetails:
    name : "Utkarsh Kumar Verma"
    email : "vermau2k01@gmail.com"
  onCallSupport:
    - "+91 9905893940"
    - "+91 7209806738"