spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3305/accountsProd
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect


server:
  port: 8080

build:
  version: "1.0"

accounts:
  message: "Welcome to QBank related prod APIs"
  contactDetails:
    name : "Utkarsh Kumar Verma"
    email : "vermau2k01@gmail.com"
  onCallSupport:
    - "+91 9905893940"
    - "+91 7209806738"