spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3304/cardsDev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect


server:
  port: 8085

build:
  version: "1.0"

cards:
  message: "Welcome to QBank related dev APIs"
  contactDetails:
    name : "Utkarsh Kumar Verma"
    email : "vermau2k01@gmail.com"
  onCallSupport:
    - "+91 9905893940"
    - "+91 7209806738"