spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3307/loansQa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect


server:
  port: 8086

build:
  version : "1.0"

loans:
  message: "Welcome to QBank related qa APIs"
  contactDetails:
    name : "Utkarsh Kumar Verma"
    email : "vermau2k01@gmail.com"
  onCallSupport:
    - "+91 9905893940"
    - "+91 7209806738"